version: '3'

services:
  class-organizer-db:
    image: mariadb:latest
    container_name: class-organizer-db
    hostname: class-organizer-db
    volumes:
      - class-organizer-db-data:/var/lib/mysql
    networks:
      - default
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: supersecretpassword
      MYSQL_DATABASE: db
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword

  class-organizer:
    depends_on:
      - class-organizer-db
    image: nextcloud:latest
    container_name: class-organizer
    hostname: class_organizer
    networks:
      - proxy
      - default
    restart: always
    #       ports:
    #            - 9443:80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.rule=Host(`class_organizer.oualid.games`)"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=8080"
      - "traefik.docker.network=proxy"

    environment:
      MYSQL_HOST: nextcloud-db:3306
      MYSQL_DATABASE: db
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword

networks:
  proxy:
    external: true

volumes:
  class-organizer-db-data: