version: '3'

services:
  class-organiser-db:
    image: mariadb:latest
    container_name: class-organiser-db
    hostname: class-organiser-db
    volumes:
      - class-organiser-db-data:/var/lib/mysql
    networks:
      - default
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: supersecretpassword
      MYSQL_DATABASE: db
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword

  class-organiser:
    depends_on:
      - class-organiser-db
    image: class-organiser:0.0.1
    container_name: class-organiser
    hostname: class-organiser
    platform: linux/amd64
    networks:
      - proxy
      - default
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.class-organiser.entrypoints=websecure"
      - "traefik.http.routers.class-organiser.rule=Host(`class-organiser.oualid.games`)"
      - "traefik.http.services.class-organiser.loadbalancer.server.port=8080"
      - "traefik.docker.network=proxy"

    environment:
      spring.datasource.url:jdbc: mysql://class-organiser-db:3306/db
      spring.datasource.username: dbuser
      spring.datasource.password: dbpassword

networks:
  proxy:
    external: true

volumes:
  class-organiser-db-data: